<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE personas[
    <!ELEMENT personas (nodo)*>
    <!ELEMENT nodo (comentario , imagen)>
    <!ELEMENT imagen (#PCDATA)>
    <!ELEMENT comentario ANY>
    <!ELEMENT p ANY>
    ]>
<personas>
	<nodo>
		<comentario>Nuestro estudio es propiedad y está dirigido por su equipo
			de directores de larga data que son líderes reconocidos en sus
			respectivos campos. Reuniendo experiencia creativa, técnica y de
			gestión, su enfoque holístico mejora el proceso de diseño y
			construcción y contribuye al éxito de cada proyecto.</comentario>
		<imagen>../imagenes/art.jpg</imagen>
	</nodo>
	<nodo>
		<comentario>
			<p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nisi, 
				deleniti tenetur iusto impedit magnam consequuntur molestiae 
				explicabo sed itaque harum hic quod sunt dolorem rerum ab repellat 
				corrupti? Quia, vitae.</p>
			<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam qui
				 quos expedita incidunt pariatur perferendis ipsum iure. Similique
				  esse, animi porro perferendis minus doloremque vitae atque at magnam
				   quo inventore earum dolor beatae? A nam autem aut, dolores pariatur 
				   qui facilis dicta corrupti quaerat architecto assumenda! 
				   Aut dolorum voluptate reiciendis laudantium temporibus laboriosam consectetur 
				   modi nemo deleniti iure, libero, porro pariatur error fugiat aspernatur 
				   necessitatibus iste sed odit fuga eveniet impedit nulla repudiandae accusantium? 
				   Obcaecati nostrum eius architecto ratione, inventore accusantium tenetur 
				   et doloribus omnis est ducimus repellendus porro tempora nobis corrupti 
				   adipisci reprehenderit molestiae id magni provident perferendis magnam?</p>
		</comentario>
		<imagen>../imagenes/people.jpg</imagen>
	</nodo>
	<nodo>
		<comentario>
			Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis nobis inventore 
			perspiciatis, accusantium maiores cum veritatis provident consectetur ad soluta 
			possimus harum quia molestiae, neque, ducimus odit! Voluptas numquam nihil laudantium
			 omnis eligendi fugiat nostrum debitis quia quasi ut deserunt, consequatur 
			 recusandae et corporis nobis facere enim explicabo sit quisquam sapiente non 
			 praesentium excepturi minus blanditiis. Maxime alias dolorum eligendi tempora et 
			 consequatur exercitationem magnam asperiores cumque, facilis sint, quibusdam, 
			 eveniet blanditiis expedita excepturi vitae repellendus modi! Quod alias temporibus sit 
			 quas, numquam ipsum modi! Eaque, molestias saepe facere nihil officia nulla ullam 
			 rem ab cupiditate non, sit aut, reiciendis delectus est pariatur libero sapiente 
			 excepturi explicabo aspernatur dolor! Aperiam et repellat aspernatur voluptates eum!
			Repellendus tempore incidunt corporis eveniet.
		</comentario>
		<imagen>../imagenes/personaje1.jpeg</imagen>
	</nodo>
</personas>


